on: [push, workflow_dispatch]

jobs:
  cognition-deploy:
    runs-on: ubuntu-latest
    name: Deploy experiment to Cognition
    steps:
      - uses: actions/checkout@v3
      
      # Step to run the Python script
      - name: Run trial generation script
        run: python3 scripts/generate_trials.py

      # Step to replace the content of the repo with the content of the www/ folder
      - name: Replace repo content with www folder content
        run: |
          tmp_dir=$(mktemp -d)
          mv * "$tmp_dir"
          mv "$tmp_dir"/www/* .
      
      - uses: javidalpe/cognition-deploy-action@v1.1.2
        id: deploy
        with:
          personal-access-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      # Manually upload json files as the above script does not do it on its own
      # - name: Upload json file
      #   run: |
      #     curl -i -X POST "https://www.cognition.run:443/external/api/github/v1/resource/${{ github.event.repository.name }}" -H "Authorization: Bearer ${{secrets.PERSONAL_ACCESS_TOKEN}}" -F "jspsych_version=7.3" -F "ignore_js=true" -F "file=@trials.js;filename=trials.js"


